// src/render/textures/index.ts
import { TextureData } from './noise';
import {
  genGrassTop,
  genGrassSide,
  genDirt,
  genFoundationStone,
  genStone,
  genCobblestone,
  genSand,
  genGravel,
  genGlass,
  PAL_STONE,
  PAL_FOUNDATION_STONE,
  PAL_DIRT,
  PAL_GRASS,
  PAL_SAND,
  PAL_GRAVEL,
  PAL_GLASS_FRAME,
  PAL_GLASS_GLINT,
  PAL_GLASS_PANE,
} from './terrain';
import {
  genOakLogTop,
  genOakLogSide,
  genBirchLogTop,
  genBirchLogSide,
  genPineLogTop,
  genPineLogSide,
  genOakPlanks,
  genBirchPlanks,
  genPinePlanks,
  genOakLeaves,
  genBirchLeaves,
  genPineLeaves,
  PAL_OAK_BARK,
  PAL_OAK_WOOD,
  PAL_BIRCH_BARK,
  PAL_BIRCH_WOOD,
  PAL_PINE_BARK,
  PAL_PINE_WOOD,
  PAL_LEAVES,
  PAL_OAK_LEAVES,
  PAL_LEAVES_TRANS,
} from './wood';
import {
  genCoalOre,
  genCopperOre,
  genIronOre,
  genGoldOre,
  genLumiteOre,
  genSkyshardOre,
  PAL_COAL,
  PAL_COPPER,
  PAL_IRON,
  PAL_GOLD,
  PAL_LUMITE,
  PAL_SKYSHARD,
} from './ores';
import { genWaterFrames, genLavaFrames, PAL_WATER, PAL_LAVA } from './fluids';
import {
  genRedSand,
  genClay,
  genSnow,
  genMire,
  genClayrockWhite,
  genClayrockLightGray,
  genClayrockYellow,
  genClayrockOrange,
  genClayrockTerracotta,
  genClayrockRed,
  genClayrockBrown,
  genClayrockDarkBrown,
  PAL_RED_SAND,
  PAL_CLAY,
  PAL_SNOW,
  PAL_MIRE,
  PAL_CLAYROCK_WHITE,
  PAL_CLAYROCK_LIGHT_GRAY,
  PAL_CLAYROCK_YELLOW,
  PAL_CLAYROCK_ORANGE,
  PAL_CLAYROCK_TERRACOTTA,
  PAL_CLAYROCK_RED,
  PAL_CLAYROCK_BROWN,
  PAL_CLAYROCK_DARK_BROWN,
} from './biome-surface';

import {
  genTallGrass,
  genBluebell,
  genButtercup,
  genMarigold,
  genViolet,
  genDaisy,
  genWildRose,
  genLupine,
  genHeather,
  genSugarReeds,
  genBrownMushroom,
  genRedMushroom,
  genCactusSide,
  genCactusTop,
  genPumpkinSide,
  genPumpkinTop,
  genMossyCobblestone,
  genPackedIce,
  PAL_TALL_GRASS,
  PAL_BLUEBELL,
  PAL_BUTTERCUP,
  PAL_MARIGOLD,
  PAL_VIOLET,
  PAL_DAISY,
  PAL_WILD_ROSE,
  PAL_LUPINE,
  PAL_HEATHER,
  PAL_REEDS,
  PAL_BROWN_MUSHROOM,
  PAL_RED_MUSHROOM,
  PAL_CACTUS,
  PAL_PUMPKIN,
  PAL_MOSSY,
  PAL_PACKED_ICE,
} from './vegetation';
import {
  genRainwoodLogTop,
  genRainwoodLogSide,
  genAcaciaLogTop,
  genAcaciaLogSide,
  genRainwoodLeaves,
  genAcaciaLeaves,
  PAL_RAINWOOD_BARK,
  PAL_RAINWOOD_WOOD,
  PAL_ACACIA_BARK,
  PAL_ACACIA_WOOD,
  PAL_RAINWOOD_LEAVES,
  PAL_ACACIA_LEAVES,
} from './wood-extra';

export type TextureGenerator = (seed?: number) => TextureData | TextureData[];

export const textureGenerators: Record<string, TextureGenerator> = {
  // Terrain
  grass_top: genGrassTop,
  grass_side: genGrassSide,
  dirt: genDirt,
  foundation_stone: genFoundationStone,
  stone: genStone,
  cobblestone: genCobblestone,
  sand: genSand,
  gravel: genGravel,
  glass: genGlass,

  // Biome surface additions
  red_sand: genRedSand,
  clay: genClay,
  snow: genSnow,
  mire: genMire,
  clayrock_white: genClayrockWhite,
  clayrock_light_gray: genClayrockLightGray,
  clayrock_yellow: genClayrockYellow,
  clayrock_orange: genClayrockOrange,
  clayrock_terracotta: genClayrockTerracotta,
  clayrock_red: genClayrockRed,
  clayrock_brown: genClayrockBrown,
  clayrock_dark_brown: genClayrockDarkBrown,

  // Wood
  oak_log_top: genOakLogTop,
  oak_log_side: genOakLogSide,
  birch_log_top: genBirchLogTop,
  birch_log_side: genBirchLogSide,
  pine_log_top: genPineLogTop,
  pine_log_side: genPineLogSide,
  oak_planks: genOakPlanks,
  birch_planks: genBirchPlanks,
  pine_planks: genPinePlanks,
  oak_leaves: genOakLeaves,
  birch_leaves: genBirchLeaves,
  pine_leaves: genPineLeaves,

  // Wood additions (M03f)
  rainwood_log_top: genRainwoodLogTop,
  rainwood_log_side: genRainwoodLogSide,
  acacia_log_top: genAcaciaLogTop,
  acacia_log_side: genAcaciaLogSide,
  rainwood_leaves: genRainwoodLeaves,
  acacia_leaves: genAcaciaLeaves,

  // Vegetation and other surface features (M03f)
  tall_grass: genTallGrass,
  bluebell: genBluebell,
  buttercup: genButtercup,
  marigold: genMarigold,
  violet: genViolet,
  daisy: genDaisy,
  wild_rose: genWildRose,
  lupine: genLupine,
  heather: genHeather,
  sugar_reeds: genSugarReeds,
  brown_mushroom: genBrownMushroom,
  red_mushroom: genRedMushroom,
  cactus_top: genCactusTop,
  cactus_side: genCactusSide,
  pumpkin_top: genPumpkinTop,
  pumpkin_side: genPumpkinSide,
  mossy_cobblestone: genMossyCobblestone,
  packed_ice: genPackedIce,

  // Ores
  coal_ore: genCoalOre,
  copper_ore: genCopperOre,
  iron_ore: genIronOre,
  gold_ore: genGoldOre,
  lumite_ore: genLumiteOre,
  skyshard_ore: genSkyshardOre,

  // Fluids
  water: genWaterFrames,
  lava: genLavaFrames,
};

// Required names by M01b Scope + M03c additions:
export const M01_REQUIRED_TEXTURES = [
  'grass_top',
  'grass_side',
  'dirt',
  'foundation_stone',
  'stone',
  'cobblestone',
  'sand',
  'gravel',
  'red_sand',
  'clay',
  'snow',
  'mire',
  'clayrock_white',
  'clayrock_light_gray',
  'clayrock_yellow',
  'clayrock_orange',
  'clayrock_terracotta',
  'clayrock_red',
  'clayrock_brown',
  'clayrock_dark_brown',
  'oak_log_top',
  'oak_log_side',
  'birch_log_top',
  'birch_log_side',
  'pine_log_top',
  'pine_log_side',
  'oak_leaves',
  'birch_leaves',
  'pine_leaves',
  'oak_planks',
  'birch_planks',
  'pine_planks',
  'glass',
  'water',
  'lava',
  'rainwood_log_top',
  'rainwood_log_side',
  'acacia_log_top',
  'acacia_log_side',
  'rainwood_leaves',
  'acacia_leaves',
  'tall_grass',
  'bluebell',
  'buttercup',
  'marigold',
  'violet',
  'daisy',
  'wild_rose',
  'lupine',
  'heather',
  'sugar_reeds',
  'brown_mushroom',
  'red_mushroom',
  'cactus_top',
  'cactus_side',
  'pumpkin_top',
  'pumpkin_side',
  'mossy_cobblestone',
  'packed_ice',
  'coal_ore',
  'copper_ore',
  'iron_ore',
  'gold_ore',
  'lumite_ore',
  'skyshard_ore',
];

import { RGBA } from './noise';

export const texturePalettes: Record<string, RGBA[]> = {
  // Terrain
  grass_top: PAL_GRASS,
  grass_side: [
    ...PAL_GRASS.map((c) => [c[0], c[1], c[2], 255] as RGBA),
    ...PAL_DIRT.map((c) => [c[0], c[1], c[2], 0] as RGBA),
  ],
  dirt: PAL_DIRT,
  foundation_stone: PAL_FOUNDATION_STONE,
  stone: PAL_STONE,
  cobblestone: PAL_STONE,
  sand: PAL_SAND,
  gravel: PAL_GRAVEL,
  glass: [PAL_GLASS_FRAME, PAL_GLASS_GLINT, PAL_GLASS_PANE],

  // Biome surface
  red_sand: PAL_RED_SAND,
  clay: PAL_CLAY,
  snow: PAL_SNOW,
  mire: PAL_MIRE,
  clayrock_white: PAL_CLAYROCK_WHITE,
  clayrock_light_gray: PAL_CLAYROCK_LIGHT_GRAY,
  clayrock_yellow: PAL_CLAYROCK_YELLOW,
  clayrock_orange: PAL_CLAYROCK_ORANGE,
  clayrock_terracotta: PAL_CLAYROCK_TERRACOTTA,
  clayrock_red: PAL_CLAYROCK_RED,
  clayrock_brown: PAL_CLAYROCK_BROWN,
  clayrock_dark_brown: PAL_CLAYROCK_DARK_BROWN,

  // Wood
  oak_log_top: [...PAL_OAK_WOOD, ...PAL_OAK_BARK],
  oak_log_side: PAL_OAK_BARK,
  birch_log_top: [...PAL_BIRCH_WOOD, ...PAL_BIRCH_BARK],
  birch_log_side: PAL_BIRCH_BARK,
  pine_log_top: [...PAL_PINE_WOOD, ...PAL_PINE_BARK],
  pine_log_side: PAL_PINE_BARK,
  oak_planks: PAL_OAK_WOOD,
  birch_planks: PAL_BIRCH_WOOD,
  pine_planks: PAL_PINE_WOOD,
  oak_leaves: [...PAL_OAK_LEAVES, PAL_LEAVES_TRANS],
  birch_leaves: [...PAL_LEAVES, PAL_LEAVES_TRANS],
  pine_leaves: [...PAL_LEAVES, PAL_LEAVES_TRANS],

  // Wood additions (M03f)
  rainwood_log_top: [...PAL_RAINWOOD_WOOD, ...PAL_RAINWOOD_BARK],
  rainwood_log_side: PAL_RAINWOOD_BARK,
  acacia_log_top: [...PAL_ACACIA_WOOD, ...PAL_ACACIA_BARK],
  acacia_log_side: PAL_ACACIA_BARK,
  rainwood_leaves: PAL_RAINWOOD_LEAVES,
  acacia_leaves: PAL_ACACIA_LEAVES,

  // Vegetation and other surface features (M03f)
  tall_grass: PAL_TALL_GRASS,
  bluebell: PAL_BLUEBELL,
  buttercup: PAL_BUTTERCUP,
  marigold: PAL_MARIGOLD,
  violet: PAL_VIOLET,
  daisy: PAL_DAISY,
  wild_rose: PAL_WILD_ROSE,
  lupine: PAL_LUPINE,
  heather: PAL_HEATHER,
  sugar_reeds: PAL_REEDS,
  brown_mushroom: PAL_BROWN_MUSHROOM,
  red_mushroom: PAL_RED_MUSHROOM,
  cactus_top: PAL_CACTUS,
  cactus_side: PAL_CACTUS,
  pumpkin_top: PAL_PUMPKIN,
  pumpkin_side: PAL_PUMPKIN,
  mossy_cobblestone: PAL_MOSSY,
  packed_ice: PAL_PACKED_ICE,

  // Ores
  coal_ore: [...PAL_STONE, ...PAL_COAL],
  copper_ore: [...PAL_STONE, ...PAL_COPPER],
  iron_ore: [...PAL_STONE, ...PAL_IRON],
  gold_ore: [...PAL_STONE, ...PAL_GOLD],
  lumite_ore: [...PAL_STONE, ...PAL_LUMITE],
  skyshard_ore: [...PAL_STONE, ...PAL_SKYSHARD],

  // Fluids
  water: PAL_WATER,
  lava: PAL_LAVA,
};
